### ISSUE TITLE
Classnames should be rendered as hyperlinks in the documentation

### ISSUE THREAD

**Issue by BenceKovari** [sigstat/sigstat#3]
e.g.: on the page https://github.com/sigstat/sigstat/wiki/SigStat.Common.PipelineItems.Classifiers the interface names could point to their respective documentation pages

**Comment by BenceKovari** [comment]
Based on previous tests, documentation should be moved to markdown, using the markdown generator nuget package

**Comment by hargitomi97** [comment]
Two problems with the new documentation format:

1) AppVeyor triggers a new build after every push, infinite building. Can't fix it due to [this](https://www.appveyor.com/docs/how-to/filtering-commits/). Probable solutions: Init git repo on GitHub or generating documentation locally.

2) Generating the documentation always creates a new commit, and devs are always forced to pull the project before pushing.

New documentation format can be found in docs/md. Removed old generator, warning message when building our page is gone.

**Comment by BenceKovari** [comment]
remove documentation generation from appveyor build, make it a local script

**Comment by hargitomi97** [comment]
Local script added and many bugs fixed thanks to the collaboration with the developer.

**Comment by BenceKovari** [comment]
Great script, please make sure that you do not build the project unnecessarily

**Comment by hargitomi97** [comment]
Removed the additional build command, final solution can be viewed [here](https://github.com/sigstat/sigstat/tree/master/docs/md).
